//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ciro.Clients {
    
    
    public partial class login {
        
        /// <summary>
        /// name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText name;
        
        /// <summary>
<<<<<<< HEAD
        /// name2 control.
=======
        /// password control.
>>>>>>> 8f6445e3901c44fb9322d5e00765e85cffa47959
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword name2;
=======
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword password;
>>>>>>> 8f6445e3901c44fb9322d5e00765e85cffa47959
    }
}
