//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ciro.CiroService {
<<<<<<< HEAD
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> product_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.productlog[] productlogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.producttype producttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> producttype_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.releaserequest[] releaserequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.transferlist[] transferlistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.transferrequest[] transferrequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_nameField, value) != true)) {
                    this.product_nameField = value;
                    this.RaisePropertyChanged("product_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> product_price {
            get {
                return this.product_priceField;
            }
            set {
                if ((this.product_priceField.Equals(value) != true)) {
                    this.product_priceField = value;
                    this.RaisePropertyChanged("product_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_quantity {
            get {
                return this.product_quantityField;
            }
            set {
                if ((this.product_quantityField.Equals(value) != true)) {
                    this.product_quantityField = value;
                    this.RaisePropertyChanged("product_quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.productlog[] productlogs {
            get {
                return this.productlogsField;
            }
            set {
                if ((object.ReferenceEquals(this.productlogsField, value) != true)) {
                    this.productlogsField = value;
                    this.RaisePropertyChanged("productlogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.producttype producttype {
            get {
                return this.producttypeField;
            }
            set {
                if ((object.ReferenceEquals(this.producttypeField, value) != true)) {
                    this.producttypeField = value;
                    this.RaisePropertyChanged("producttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> producttype_id {
            get {
                return this.producttype_idField;
            }
            set {
                if ((this.producttype_idField.Equals(value) != true)) {
                    this.producttype_idField = value;
                    this.RaisePropertyChanged("producttype_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.releaserequest[] releaserequests {
            get {
                return this.releaserequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.releaserequestsField, value) != true)) {
                    this.releaserequestsField = value;
                    this.RaisePropertyChanged("releaserequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.transferlist[] transferlists {
            get {
                return this.transferlistsField;
            }
            set {
                if ((object.ReferenceEquals(this.transferlistsField, value) != true)) {
                    this.transferlistsField = value;
                    this.RaisePropertyChanged("transferlists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.transferrequest[] transferrequests {
            get {
                return this.transferrequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.transferrequestsField, value) != true)) {
                    this.transferrequestsField = value;
                    this.RaisePropertyChanged("transferrequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="producttype", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class producttype : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.product[] productsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int producttype_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string producttype_typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.product[] products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int producttype_id {
            get {
                return this.producttype_idField;
            }
            set {
                if ((this.producttype_idField.Equals(value) != true)) {
                    this.producttype_idField = value;
                    this.RaisePropertyChanged("producttype_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producttype_type {
            get {
                return this.producttype_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.producttype_typeField, value) != true)) {
                    this.producttype_typeField = value;
                    this.RaisePropertyChanged("producttype_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.invoice[] invoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.product[] productsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.releaserequest[] releaserequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.transferrequest[] transferrequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_fnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_snameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.usertype usertypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int usertype_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.invoice[] invoices {
            get {
                return this.invoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.invoicesField, value) != true)) {
                    this.invoicesField = value;
                    this.RaisePropertyChanged("invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.product[] products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.releaserequest[] releaserequests {
            get {
                return this.releaserequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.releaserequestsField, value) != true)) {
                    this.releaserequestsField = value;
                    this.RaisePropertyChanged("releaserequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.transferrequest[] transferrequests {
            get {
                return this.transferrequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.transferrequestsField, value) != true)) {
                    this.transferrequestsField = value;
                    this.RaisePropertyChanged("transferrequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_email {
            get {
                return this.user_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.user_emailField, value) != true)) {
                    this.user_emailField = value;
                    this.RaisePropertyChanged("user_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_fname {
            get {
                return this.user_fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_fnameField, value) != true)) {
                    this.user_fnameField = value;
                    this.RaisePropertyChanged("user_fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_password {
            get {
                return this.user_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.user_passwordField, value) != true)) {
                    this.user_passwordField = value;
                    this.RaisePropertyChanged("user_password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_sname {
            get {
                return this.user_snameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_snameField, value) != true)) {
                    this.user_snameField = value;
                    this.RaisePropertyChanged("user_sname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.usertype usertype {
            get {
                return this.usertypeField;
            }
            set {
                if ((object.ReferenceEquals(this.usertypeField, value) != true)) {
                    this.usertypeField = value;
                    this.RaisePropertyChanged("usertype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int usertype_id {
            get {
                return this.usertype_idField;
            }
            set {
                if ((this.usertype_idField.Equals(value) != true)) {
                    this.usertype_idField = value;
                    this.RaisePropertyChanged("usertype_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productlog", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class productlog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.product productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productlog_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productlog_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productlog_description {
            get {
                return this.productlog_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.productlog_descriptionField, value) != true)) {
                    this.productlog_descriptionField = value;
                    this.RaisePropertyChanged("productlog_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productlog_id {
            get {
                return this.productlog_idField;
            }
            set {
                if ((this.productlog_idField.Equals(value) != true)) {
                    this.productlog_idField = value;
                    this.RaisePropertyChanged("productlog_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="releaserequest", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class releaserequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.product productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_id_releaserequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string releaserequest_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int releaserequest_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_id_releaserequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_id_releaserequest {
            get {
                return this.product_id_releaserequestField;
            }
            set {
                if ((this.product_id_releaserequestField.Equals(value) != true)) {
                    this.product_id_releaserequestField = value;
                    this.RaisePropertyChanged("product_id_releaserequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string releaserequest_description {
            get {
                return this.releaserequest_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.releaserequest_descriptionField, value) != true)) {
                    this.releaserequest_descriptionField = value;
                    this.RaisePropertyChanged("releaserequest_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int releaserequest_id {
            get {
                return this.releaserequest_idField;
            }
            set {
                if ((this.releaserequest_idField.Equals(value) != true)) {
                    this.releaserequest_idField = value;
                    this.RaisePropertyChanged("releaserequest_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id_releaserequest {
            get {
                return this.user_id_releaserequestField;
            }
            set {
                if ((this.user_id_releaserequestField.Equals(value) != true)) {
                    this.user_id_releaserequestField = value;
                    this.RaisePropertyChanged("user_id_releaserequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="transferlist", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class transferlist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.product productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_id_transferlistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferlist_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferlist_fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int transferlist_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferlist_toField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.warehouse warehouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> warehouse_id_transferlistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_id_transferlist {
            get {
                return this.product_id_transferlistField;
            }
            set {
                if ((this.product_id_transferlistField.Equals(value) != true)) {
                    this.product_id_transferlistField = value;
                    this.RaisePropertyChanged("product_id_transferlist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferlist_description {
            get {
                return this.transferlist_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.transferlist_descriptionField, value) != true)) {
                    this.transferlist_descriptionField = value;
                    this.RaisePropertyChanged("transferlist_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferlist_from {
            get {
                return this.transferlist_fromField;
            }
            set {
                if ((object.ReferenceEquals(this.transferlist_fromField, value) != true)) {
                    this.transferlist_fromField = value;
                    this.RaisePropertyChanged("transferlist_from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int transferlist_id {
            get {
                return this.transferlist_idField;
            }
            set {
                if ((this.transferlist_idField.Equals(value) != true)) {
                    this.transferlist_idField = value;
                    this.RaisePropertyChanged("transferlist_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferlist_to {
            get {
                return this.transferlist_toField;
            }
            set {
                if ((object.ReferenceEquals(this.transferlist_toField, value) != true)) {
                    this.transferlist_toField = value;
                    this.RaisePropertyChanged("transferlist_to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.warehouse warehouse {
            get {
                return this.warehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.warehouseField, value) != true)) {
                    this.warehouseField = value;
                    this.RaisePropertyChanged("warehouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> warehouse_id_transferlist {
            get {
                return this.warehouse_id_transferlistField;
            }
            set {
                if ((this.warehouse_id_transferlistField.Equals(value) != true)) {
                    this.warehouse_id_transferlistField = value;
                    this.RaisePropertyChanged("warehouse_id_transferlist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="transferrequest", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class transferrequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> package_id_transferrequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.product productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferrequest_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferrequest_fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int transferrequest_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferrequest_toField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_id_transferrequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> package_id_transferrequest {
            get {
                return this.package_id_transferrequestField;
            }
            set {
                if ((this.package_id_transferrequestField.Equals(value) != true)) {
                    this.package_id_transferrequestField = value;
                    this.RaisePropertyChanged("package_id_transferrequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferrequest_description {
            get {
                return this.transferrequest_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.transferrequest_descriptionField, value) != true)) {
                    this.transferrequest_descriptionField = value;
                    this.RaisePropertyChanged("transferrequest_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferrequest_from {
            get {
                return this.transferrequest_fromField;
            }
            set {
                if ((object.ReferenceEquals(this.transferrequest_fromField, value) != true)) {
                    this.transferrequest_fromField = value;
                    this.RaisePropertyChanged("transferrequest_from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int transferrequest_id {
            get {
                return this.transferrequest_idField;
            }
            set {
                if ((this.transferrequest_idField.Equals(value) != true)) {
                    this.transferrequest_idField = value;
                    this.RaisePropertyChanged("transferrequest_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferrequest_to {
            get {
                return this.transferrequest_toField;
            }
            set {
                if ((object.ReferenceEquals(this.transferrequest_toField, value) != true)) {
                    this.transferrequest_toField = value;
                    this.RaisePropertyChanged("transferrequest_to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id_transferrequest {
            get {
                return this.user_id_transferrequestField;
            }
            set {
                if ((this.user_id_transferrequestField.Equals(value) != true)) {
                    this.user_id_transferrequestField = value;
                    this.RaisePropertyChanged("user_id_transferrequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usertype", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class usertype : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.user[] usersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int usertype_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usertype_typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.user[] users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int usertype_id {
            get {
                return this.usertype_idField;
            }
            set {
                if ((this.usertype_idField.Equals(value) != true)) {
                    this.usertype_idField = value;
                    this.RaisePropertyChanged("usertype_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usertype_type {
            get {
                return this.usertype_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.usertype_typeField, value) != true)) {
                    this.usertype_typeField = value;
                    this.RaisePropertyChanged("usertype_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invoice", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoice_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int invoice_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> invoice_totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_id_invoiceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice_description {
            get {
                return this.invoice_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.invoice_descriptionField, value) != true)) {
                    this.invoice_descriptionField = value;
                    this.RaisePropertyChanged("invoice_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int invoice_id {
            get {
                return this.invoice_idField;
            }
            set {
                if ((this.invoice_idField.Equals(value) != true)) {
                    this.invoice_idField = value;
                    this.RaisePropertyChanged("invoice_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> invoice_total {
            get {
                return this.invoice_totalField;
            }
            set {
                if ((this.invoice_totalField.Equals(value) != true)) {
                    this.invoice_totalField = value;
                    this.RaisePropertyChanged("invoice_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id_invoice {
            get {
                return this.user_id_invoiceField;
            }
            set {
                if ((this.user_id_invoiceField.Equals(value) != true)) {
                    this.user_id_invoiceField = value;
                    this.RaisePropertyChanged("user_id_invoice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="warehouse", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class warehouse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.transferlist[] transferlistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int warehouse_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string warehouse_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string warehouse_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> warehouse_sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> warehouse_warehousetypeidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.warehousetype warehousetypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.transferlist[] transferlists {
            get {
                return this.transferlistsField;
            }
            set {
                if ((object.ReferenceEquals(this.transferlistsField, value) != true)) {
                    this.transferlistsField = value;
                    this.RaisePropertyChanged("transferlists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int warehouse_id {
            get {
                return this.warehouse_idField;
            }
            set {
                if ((this.warehouse_idField.Equals(value) != true)) {
                    this.warehouse_idField = value;
                    this.RaisePropertyChanged("warehouse_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string warehouse_location {
            get {
                return this.warehouse_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.warehouse_locationField, value) != true)) {
                    this.warehouse_locationField = value;
                    this.RaisePropertyChanged("warehouse_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string warehouse_name {
            get {
                return this.warehouse_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.warehouse_nameField, value) != true)) {
                    this.warehouse_nameField = value;
                    this.RaisePropertyChanged("warehouse_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> warehouse_size {
            get {
                return this.warehouse_sizeField;
            }
            set {
                if ((this.warehouse_sizeField.Equals(value) != true)) {
                    this.warehouse_sizeField = value;
                    this.RaisePropertyChanged("warehouse_size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> warehouse_warehousetypeid {
            get {
                return this.warehouse_warehousetypeidField;
            }
            set {
                if ((this.warehouse_warehousetypeidField.Equals(value) != true)) {
                    this.warehouse_warehousetypeidField = value;
                    this.RaisePropertyChanged("warehouse_warehousetypeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.warehousetype warehousetype {
            get {
                return this.warehousetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.warehousetypeField, value) != true)) {
                    this.warehousetypeField = value;
                    this.RaisePropertyChanged("warehousetype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="warehousetype", Namespace="http://schemas.datacontract.org/2004/07/CiroService.EFDatabase")]
    [System.SerializableAttribute()]
    public partial class warehousetype : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project_Ciro.CiroService.warehouse[] warehousesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int warehousetype_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string warehousetype_typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project_Ciro.CiroService.warehouse[] warehouses {
            get {
                return this.warehousesField;
            }
            set {
                if ((object.ReferenceEquals(this.warehousesField, value) != true)) {
                    this.warehousesField = value;
                    this.RaisePropertyChanged("warehouses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int warehousetype_id {
            get {
                return this.warehousetype_idField;
            }
            set {
                if ((this.warehousetype_idField.Equals(value) != true)) {
                    this.warehousetype_idField = value;
                    this.RaisePropertyChanged("warehousetype_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string warehousetype_type {
            get {
                return this.warehousetype_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.warehousetype_typeField, value) != true)) {
                    this.warehousetype_typeField = value;
                    this.RaisePropertyChanged("warehousetype_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CiroService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
=======
    
    
>>>>>>> 8f6445e3901c44fb9322d5e00765e85cffa47959
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CiroService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
<<<<<<< HEAD
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        string login(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listProduct", ReplyAction="http://tempuri.org/IService1/listProductResponse")]
        Project_Ciro.CiroService.product[] listProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listProduct", ReplyAction="http://tempuri.org/IService1/listProductResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.product[]> listProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Project_Ciro.CiroService.CompositeType GetDataUsingDataContract(Project_Ciro.CiroService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.CompositeType> GetDataUsingDataContractAsync(Project_Ciro.CiroService.CompositeType composite);
=======
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        string login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientProducts", ReplyAction="http://tempuri.org/IService1/clientProductsResponse")]
        string clientProducts(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientProducts", ReplyAction="http://tempuri.org/IService1/clientProductsResponse")]
        System.Threading.Tasks.Task<string> clientProductsAsync(string id);
>>>>>>> 8f6445e3901c44fb9322d5e00765e85cffa47959
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project_Ciro.CiroService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project_Ciro.CiroService.IService1>, Project_Ciro.CiroService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
<<<<<<< HEAD
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string login(string user, string password) {
            return base.Channel.login(user, password);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string user, string password) {
            return base.Channel.loginAsync(user, password);
        }
        
        public Project_Ciro.CiroService.product[] listProduct() {
            return base.Channel.listProduct();
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.product[]> listProductAsync() {
            return base.Channel.listProductAsync();
        }
        
        public Project_Ciro.CiroService.CompositeType GetDataUsingDataContract(Project_Ciro.CiroService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.CompositeType> GetDataUsingDataContractAsync(Project_Ciro.CiroService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
=======
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public string login(string name, string password) {
            return base.Channel.login(name, password);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string name, string password) {
            return base.Channel.loginAsync(name, password);
        }
        
        public string clientProducts(string id) {
            return base.Channel.clientProducts(id);
        }
        
        public System.Threading.Tasks.Task<string> clientProductsAsync(string id) {
            return base.Channel.clientProductsAsync(id);
>>>>>>> 8f6445e3901c44fb9322d5e00765e85cffa47959
        }
    }
}
