//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ciro.CiroService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jsonLoginUser", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class jsonLoginUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jsonLogin", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class jsonLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jsonProduct", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class jsonProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currentLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.currentLocationField, value) != true)) {
                    this.currentLocationField = value;
                    this.RaisePropertyChanged("currentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productType {
            get {
                return this.productTypeField;
            }
            set {
                if ((this.productTypeField.Equals(value) != true)) {
                    this.productTypeField = value;
                    this.RaisePropertyChanged("productType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferLocation {
            get {
                return this.transferLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.transferLocationField, value) != true)) {
                    this.transferLocationField = value;
                    this.RaisePropertyChanged("transferLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jsonTRequest", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class jsonTRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endWarehouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endWarehouse {
            get {
                return this.endWarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.endWarehouseField, value) != true)) {
                    this.endWarehouseField = value;
                    this.RaisePropertyChanged("endWarehouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferDetails", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class TransferDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currentLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.currentLocationField, value) != true)) {
                    this.currentLocationField = value;
                    this.RaisePropertyChanged("currentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                if ((object.ReferenceEquals(this.destinationField, value) != true)) {
                    this.destinationField = value;
                    this.RaisePropertyChanged("destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                if ((object.ReferenceEquals(this.productNameField, value) != true)) {
                    this.productNameField = value;
                    this.RaisePropertyChanged("productName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stockTakeInfo", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class stockTakeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jsonTask", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class jsonTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jsonIncident", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class jsonIncident : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonWarehouse", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class JsonWarehouse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int type_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                if ((this.sizeField.Equals(value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type_id {
            get {
                return this.type_idField;
            }
            set {
                if ((this.type_idField.Equals(value) != true)) {
                    this.type_idField = value;
                    this.RaisePropertyChanged("type_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="transferStock", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class transferStock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                if ((object.ReferenceEquals(this.productNameField, value) != true)) {
                    this.productNameField = value;
                    this.RaisePropertyChanged("productName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                if ((this.sizeField.Equals(value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonUser", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class JsonUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fnameField, value) != true)) {
                    this.fnameField = value;
                    this.RaisePropertyChanged("fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lnameField, value) != true)) {
                    this.lnameField = value;
                    this.RaisePropertyChanged("lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonProducts", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class JsonProducts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime arrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isInspectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int producttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime arrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                if ((this.arrivalDateField.Equals(value) != true)) {
                    this.arrivalDateField = value;
                    this.RaisePropertyChanged("arrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                if ((object.ReferenceEquals(this.destinationField, value) != true)) {
                    this.destinationField = value;
                    this.RaisePropertyChanged("destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isInspected {
            get {
                return this.isInspectedField;
            }
            set {
                if ((object.ReferenceEquals(this.isInspectedField, value) != true)) {
                    this.isInspectedField = value;
                    this.RaisePropertyChanged("isInspected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int producttype {
            get {
                return this.producttypeField;
            }
            set {
                if ((this.producttypeField.Equals(value) != true)) {
                    this.producttypeField = value;
                    this.RaisePropertyChanged("producttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonReleaseRequest", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class JsonReleaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string verdictField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string verdict {
            get {
                return this.verdictField;
            }
            set {
                if ((object.ReferenceEquals(this.verdictField, value) != true)) {
                    this.verdictField = value;
                    this.RaisePropertyChanged("verdict");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonProductLog", Namespace="http://schemas.datacontract.org/2004/07/CiroService.JsonObjects")]
    [System.SerializableAttribute()]
    public partial class JsonProductLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CiroService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        Project_Ciro.CiroService.jsonLogin login([System.ServiceModel.MessageParameterAttribute(Name="login")] Project_Ciro.CiroService.jsonLoginUser login1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.jsonLogin> loginAsync(Project_Ciro.CiroService.jsonLoginUser login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientProducts", ReplyAction="http://tempuri.org/IService1/clientProductsResponse")]
        Project_Ciro.CiroService.jsonProduct[] clientProducts(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/clientProducts", ReplyAction="http://tempuri.org/IService1/clientProductsResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.jsonProduct[]> clientProductsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transeferRequest", ReplyAction="http://tempuri.org/IService1/transeferRequestResponse")]
        string transeferRequest(Project_Ciro.CiroService.jsonTRequest newRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transeferRequest", ReplyAction="http://tempuri.org/IService1/transeferRequestResponse")]
        System.Threading.Tasks.Task<string> transeferRequestAsync(Project_Ciro.CiroService.jsonTRequest newRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transferList", ReplyAction="http://tempuri.org/IService1/transferListResponse")]
        Project_Ciro.CiroService.TransferDetails[] transferList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transferList", ReplyAction="http://tempuri.org/IService1/transferListResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.TransferDetails[]> transferListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stockTake", ReplyAction="http://tempuri.org/IService1/stockTakeResponse")]
        string stockTake([System.ServiceModel.MessageParameterAttribute(Name="stockTake")] Project_Ciro.CiroService.stockTakeInfo stockTake1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stockTake", ReplyAction="http://tempuri.org/IService1/stockTakeResponse")]
        System.Threading.Tasks.Task<string> stockTakeAsync(Project_Ciro.CiroService.stockTakeInfo stockTake);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stockAdd", ReplyAction="http://tempuri.org/IService1/stockAddResponse")]
        void stockAdd(string origin, Project_Ciro.CiroService.jsonProduct[] newProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stockAdd", ReplyAction="http://tempuri.org/IService1/stockAddResponse")]
        System.Threading.Tasks.Task stockAddAsync(string origin, Project_Ciro.CiroService.jsonProduct[] newProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/taskList", ReplyAction="http://tempuri.org/IService1/taskListResponse")]
        Project_Ciro.CiroService.jsonTask[] taskList(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/taskList", ReplyAction="http://tempuri.org/IService1/taskListResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.jsonTask[]> taskListAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addIncident", ReplyAction="http://tempuri.org/IService1/addIncidentResponse")]
        void addIncident(Project_Ciro.CiroService.jsonIncident newIncident);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addIncident", ReplyAction="http://tempuri.org/IService1/addIncidentResponse")]
        System.Threading.Tasks.Task addIncidentAsync(Project_Ciro.CiroService.jsonIncident newIncident);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/warehouseInfo", ReplyAction="http://tempuri.org/IService1/warehouseInfoResponse")]
        Project_Ciro.CiroService.JsonWarehouse warehouseInfo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/warehouseInfo", ReplyAction="http://tempuri.org/IService1/warehouseInfoResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonWarehouse> warehouseInfoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/warehouses", ReplyAction="http://tempuri.org/IService1/warehousesResponse")]
        Project_Ciro.CiroService.JsonWarehouse[] warehouses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/warehouses", ReplyAction="http://tempuri.org/IService1/warehousesResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonWarehouse[]> warehousesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stockleavingWarehouse", ReplyAction="http://tempuri.org/IService1/stockleavingWarehouseResponse")]
        Project_Ciro.CiroService.transferStock[] stockleavingWarehouse(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/stockleavingWarehouse", ReplyAction="http://tempuri.org/IService1/stockleavingWarehouseResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.transferStock[]> stockleavingWarehouseAsync(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/register", ReplyAction="http://tempuri.org/IService1/registerResponse")]
        string register(Project_Ciro.CiroService.JsonUser regUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/register", ReplyAction="http://tempuri.org/IService1/registerResponse")]
        System.Threading.Tasks.Task<string> registerAsync(Project_Ciro.CiroService.JsonUser regUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUser", ReplyAction="http://tempuri.org/IService1/updateUserResponse")]
        string updateUser(string id, Project_Ciro.CiroService.JsonUser updateUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUser", ReplyAction="http://tempuri.org/IService1/updateUserResponse")]
        System.Threading.Tasks.Task<string> updateUserAsync(string id, Project_Ciro.CiroService.JsonUser updateUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageID", ReplyAction="http://tempuri.org/IService1/getPackageIDResponse")]
        Project_Ciro.CiroService.JsonProducts getPackageID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageID", ReplyAction="http://tempuri.org/IService1/getPackageIDResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProducts> getPackageIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageType", ReplyAction="http://tempuri.org/IService1/getPackageTypeResponse")]
        Project_Ciro.CiroService.JsonProducts[] getPackageType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageType", ReplyAction="http://tempuri.org/IService1/getPackageTypeResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProducts[]> getPackageTypeAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageOwner", ReplyAction="http://tempuri.org/IService1/getPackageOwnerResponse")]
        Project_Ciro.CiroService.JsonProducts[] getPackageOwner(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageOwner", ReplyAction="http://tempuri.org/IService1/getPackageOwnerResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProducts[]> getPackageOwnerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageDate", ReplyAction="http://tempuri.org/IService1/getPackageDateResponse")]
        string getPackageDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageDate", ReplyAction="http://tempuri.org/IService1/getPackageDateResponse")]
        System.Threading.Tasks.Task<string> getPackageDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageDest", ReplyAction="http://tempuri.org/IService1/getPackageDestResponse")]
        string getPackageDest(string dest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageDest", ReplyAction="http://tempuri.org/IService1/getPackageDestResponse")]
        System.Threading.Tasks.Task<string> getPackageDestAsync(string dest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageLocation", ReplyAction="http://tempuri.org/IService1/getPackageLocationResponse")]
        string getPackageLocation(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPackageLocation", ReplyAction="http://tempuri.org/IService1/getPackageLocationResponse")]
        System.Threading.Tasks.Task<string> getPackageLocationAsync(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPackage", ReplyAction="http://tempuri.org/IService1/addPackageResponse")]
        string addPackage(Project_Ciro.CiroService.JsonProducts prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addPackage", ReplyAction="http://tempuri.org/IService1/addPackageResponse")]
        System.Threading.Tasks.Task<string> addPackageAsync(Project_Ciro.CiroService.JsonProducts prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatePackage", ReplyAction="http://tempuri.org/IService1/updatePackageResponse")]
        string updatePackage(string id, Project_Ciro.CiroService.JsonProducts prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatePackage", ReplyAction="http://tempuri.org/IService1/updatePackageResponse")]
        System.Threading.Tasks.Task<string> updatePackageAsync(string id, Project_Ciro.CiroService.JsonProducts prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatePackageWLocation", ReplyAction="http://tempuri.org/IService1/updatePackageWLocationResponse")]
        string updatePackageWLocation(string id, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatePackageWLocation", ReplyAction="http://tempuri.org/IService1/updatePackageWLocationResponse")]
        System.Threading.Tasks.Task<string> updatePackageWLocationAsync(string id, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/releaseRequest", ReplyAction="http://tempuri.org/IService1/releaseRequestResponse")]
        string releaseRequest(string uID, string pID, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/releaseRequest", ReplyAction="http://tempuri.org/IService1/releaseRequestResponse")]
        System.Threading.Tasks.Task<string> releaseRequestAsync(string uID, string pID, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRelease", ReplyAction="http://tempuri.org/IService1/getReleaseResponse")]
        Project_Ciro.CiroService.JsonReleaseRequest[] getRelease(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRelease", ReplyAction="http://tempuri.org/IService1/getReleaseResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonReleaseRequest[]> getReleaseAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProductLog", ReplyAction="http://tempuri.org/IService1/addProductLogResponse")]
        string addProductLog(string code, string description, Project_Ciro.CiroService.JsonProducts prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProductLog", ReplyAction="http://tempuri.org/IService1/addProductLogResponse")]
        System.Threading.Tasks.Task<string> addProductLogAsync(string code, string description, Project_Ciro.CiroService.JsonProducts prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductLog", ReplyAction="http://tempuri.org/IService1/getProductLogResponse")]
        Project_Ciro.CiroService.JsonProductLog[] getProductLog(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductLog", ReplyAction="http://tempuri.org/IService1/getProductLogResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProductLog[]> getProductLogAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWarehouse", ReplyAction="http://tempuri.org/IService1/getWarehouseResponse")]
        Project_Ciro.CiroService.JsonWarehouse[] getWarehouse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWarehouse", ReplyAction="http://tempuri.org/IService1/getWarehouseResponse")]
        System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonWarehouse[]> getWarehouseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveTransfer", ReplyAction="http://tempuri.org/IService1/approveTransferResponse")]
        string approveTransfer(string id, string verdict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveTransfer", ReplyAction="http://tempuri.org/IService1/approveTransferResponse")]
        System.Threading.Tasks.Task<string> approveTransferAsync(string id, string verdict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveRequest", ReplyAction="http://tempuri.org/IService1/approveRequestResponse")]
        string approveRequest(string verdict, Project_Ciro.CiroService.JsonProducts prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/approveRequest", ReplyAction="http://tempuri.org/IService1/approveRequestResponse")]
        System.Threading.Tasks.Task<string> approveRequestAsync(string verdict, Project_Ciro.CiroService.JsonProducts prod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project_Ciro.CiroService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project_Ciro.CiroService.IService1>, Project_Ciro.CiroService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public Project_Ciro.CiroService.jsonLogin login(Project_Ciro.CiroService.jsonLoginUser login1) {
            return base.Channel.login(login1);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.jsonLogin> loginAsync(Project_Ciro.CiroService.jsonLoginUser login) {
            return base.Channel.loginAsync(login);
        }
        
        public Project_Ciro.CiroService.jsonProduct[] clientProducts(string id) {
            return base.Channel.clientProducts(id);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.jsonProduct[]> clientProductsAsync(string id) {
            return base.Channel.clientProductsAsync(id);
        }
        
        public string transeferRequest(Project_Ciro.CiroService.jsonTRequest newRequest) {
            return base.Channel.transeferRequest(newRequest);
        }
        
        public System.Threading.Tasks.Task<string> transeferRequestAsync(Project_Ciro.CiroService.jsonTRequest newRequest) {
            return base.Channel.transeferRequestAsync(newRequest);
        }
        
        public Project_Ciro.CiroService.TransferDetails[] transferList() {
            return base.Channel.transferList();
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.TransferDetails[]> transferListAsync() {
            return base.Channel.transferListAsync();
        }
        
        public string stockTake(Project_Ciro.CiroService.stockTakeInfo stockTake1) {
            return base.Channel.stockTake(stockTake1);
        }
        
        public System.Threading.Tasks.Task<string> stockTakeAsync(Project_Ciro.CiroService.stockTakeInfo stockTake) {
            return base.Channel.stockTakeAsync(stockTake);
        }
        
        public void stockAdd(string origin, Project_Ciro.CiroService.jsonProduct[] newProduct) {
            base.Channel.stockAdd(origin, newProduct);
        }
        
        public System.Threading.Tasks.Task stockAddAsync(string origin, Project_Ciro.CiroService.jsonProduct[] newProduct) {
            return base.Channel.stockAddAsync(origin, newProduct);
        }
        
        public Project_Ciro.CiroService.jsonTask[] taskList(string id) {
            return base.Channel.taskList(id);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.jsonTask[]> taskListAsync(string id) {
            return base.Channel.taskListAsync(id);
        }
        
        public void addIncident(Project_Ciro.CiroService.jsonIncident newIncident) {
            base.Channel.addIncident(newIncident);
        }
        
        public System.Threading.Tasks.Task addIncidentAsync(Project_Ciro.CiroService.jsonIncident newIncident) {
            return base.Channel.addIncidentAsync(newIncident);
        }
        
        public Project_Ciro.CiroService.JsonWarehouse warehouseInfo(string id) {
            return base.Channel.warehouseInfo(id);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonWarehouse> warehouseInfoAsync(string id) {
            return base.Channel.warehouseInfoAsync(id);
        }
        
        public Project_Ciro.CiroService.JsonWarehouse[] warehouses() {
            return base.Channel.warehouses();
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonWarehouse[]> warehousesAsync() {
            return base.Channel.warehousesAsync();
        }
        
        public Project_Ciro.CiroService.transferStock[] stockleavingWarehouse(string location) {
            return base.Channel.stockleavingWarehouse(location);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.transferStock[]> stockleavingWarehouseAsync(string location) {
            return base.Channel.stockleavingWarehouseAsync(location);
        }
        
        public string register(Project_Ciro.CiroService.JsonUser regUser) {
            return base.Channel.register(regUser);
        }
        
        public System.Threading.Tasks.Task<string> registerAsync(Project_Ciro.CiroService.JsonUser regUser) {
            return base.Channel.registerAsync(regUser);
        }
        
        public string updateUser(string id, Project_Ciro.CiroService.JsonUser updateUsr) {
            return base.Channel.updateUser(id, updateUsr);
        }
        
        public System.Threading.Tasks.Task<string> updateUserAsync(string id, Project_Ciro.CiroService.JsonUser updateUsr) {
            return base.Channel.updateUserAsync(id, updateUsr);
        }
        
        public Project_Ciro.CiroService.JsonProducts getPackageID(string id) {
            return base.Channel.getPackageID(id);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProducts> getPackageIDAsync(string id) {
            return base.Channel.getPackageIDAsync(id);
        }
        
        public Project_Ciro.CiroService.JsonProducts[] getPackageType(string type) {
            return base.Channel.getPackageType(type);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProducts[]> getPackageTypeAsync(string type) {
            return base.Channel.getPackageTypeAsync(type);
        }
        
        public Project_Ciro.CiroService.JsonProducts[] getPackageOwner(string id) {
            return base.Channel.getPackageOwner(id);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProducts[]> getPackageOwnerAsync(string id) {
            return base.Channel.getPackageOwnerAsync(id);
        }
        
        public string getPackageDate(string date) {
            return base.Channel.getPackageDate(date);
        }
        
        public System.Threading.Tasks.Task<string> getPackageDateAsync(string date) {
            return base.Channel.getPackageDateAsync(date);
        }
        
        public string getPackageDest(string dest) {
            return base.Channel.getPackageDest(dest);
        }
        
        public System.Threading.Tasks.Task<string> getPackageDestAsync(string dest) {
            return base.Channel.getPackageDestAsync(dest);
        }
        
        public string getPackageLocation(string location) {
            return base.Channel.getPackageLocation(location);
        }
        
        public System.Threading.Tasks.Task<string> getPackageLocationAsync(string location) {
            return base.Channel.getPackageLocationAsync(location);
        }
        
        public string addPackage(Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.addPackage(prod);
        }
        
        public System.Threading.Tasks.Task<string> addPackageAsync(Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.addPackageAsync(prod);
        }
        
        public string updatePackage(string id, Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.updatePackage(id, prod);
        }
        
        public System.Threading.Tasks.Task<string> updatePackageAsync(string id, Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.updatePackageAsync(id, prod);
        }
        
        public string updatePackageWLocation(string id, string location) {
            return base.Channel.updatePackageWLocation(id, location);
        }
        
        public System.Threading.Tasks.Task<string> updatePackageWLocationAsync(string id, string location) {
            return base.Channel.updatePackageWLocationAsync(id, location);
        }
        
        public string releaseRequest(string uID, string pID, string description) {
            return base.Channel.releaseRequest(uID, pID, description);
        }
        
        public System.Threading.Tasks.Task<string> releaseRequestAsync(string uID, string pID, string description) {
            return base.Channel.releaseRequestAsync(uID, pID, description);
        }
        
        public Project_Ciro.CiroService.JsonReleaseRequest[] getRelease(string id) {
            return base.Channel.getRelease(id);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonReleaseRequest[]> getReleaseAsync(string id) {
            return base.Channel.getReleaseAsync(id);
        }
        
        public string addProductLog(string code, string description, Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.addProductLog(code, description, prod);
        }
        
        public System.Threading.Tasks.Task<string> addProductLogAsync(string code, string description, Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.addProductLogAsync(code, description, prod);
        }
        
        public Project_Ciro.CiroService.JsonProductLog[] getProductLog(string id) {
            return base.Channel.getProductLog(id);
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonProductLog[]> getProductLogAsync(string id) {
            return base.Channel.getProductLogAsync(id);
        }
        
        public Project_Ciro.CiroService.JsonWarehouse[] getWarehouse() {
            return base.Channel.getWarehouse();
        }
        
        public System.Threading.Tasks.Task<Project_Ciro.CiroService.JsonWarehouse[]> getWarehouseAsync() {
            return base.Channel.getWarehouseAsync();
        }
        
        public string approveTransfer(string id, string verdict) {
            return base.Channel.approveTransfer(id, verdict);
        }
        
        public System.Threading.Tasks.Task<string> approveTransferAsync(string id, string verdict) {
            return base.Channel.approveTransferAsync(id, verdict);
        }
        
        public string approveRequest(string verdict, Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.approveRequest(verdict, prod);
        }
        
        public System.Threading.Tasks.Task<string> approveRequestAsync(string verdict, Project_Ciro.CiroService.JsonProducts prod) {
            return base.Channel.approveRequestAsync(verdict, prod);
        }
    }
}
