//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class billofentry
    {
        public int billofentry_id { get; set; }
        public string billofentry_code { get; set; }
        public Nullable<int> billofentry_user { get; set; }
        public Nullable<int> billofentry_product { get; set; }
        public string billofentry_origin { get; set; }
        public string billofentry_invoice { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
