//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class custommandbEntities1 : DbContext
    {
        public custommandbEntities1()
            : base("name=custommandbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<billofentry> billofentries { get; set; }
        public DbSet<countryrelation> countryrelations { get; set; }
        public DbSet<hscode> hscodes { get; set; }
        public DbSet<invoice> invoices { get; set; }
        public DbSet<location> locations { get; set; }
        public DbSet<message> messages { get; set; }
        public DbSet<ownershiprequest> ownershiprequests { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productlog> productlogs { get; set; }
        public DbSet<productlogtype> productlogtypes { get; set; }
        public DbSet<producttype> producttypes { get; set; }
        public DbSet<releaserequest> releaserequests { get; set; }
        public DbSet<transferlist> transferlists { get; set; }
        public DbSet<transferrequest> transferrequests { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<usertype> usertypes { get; set; }
        public DbSet<warehouse> warehouses { get; set; }
        public DbSet<warehouseemployee> warehouseemployees { get; set; }
        public DbSet<warehousestock> warehousestocks { get; set; }
        public DbSet<warehousetask> warehousetasks { get; set; }
        public DbSet<warehousetype> warehousetypes { get; set; }
    }
}
