//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class hscode
    {
        public hscode()
        {
            this.countryrelations = new HashSet<countryrelation>();
            this.products = new HashSet<product>();
        }
    
        public int hscode_id { get; set; }
        public decimal hscode_percentage { get; set; }
    
        public virtual ICollection<countryrelation> countryrelations { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
