//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.billofentries = new HashSet<billofentry>();
        }
    
        public string invoice_id { get; set; }
        public Nullable<decimal> invoice_vat { get; set; }
        public Nullable<decimal> invoice_penalty { get; set; }
        public Nullable<decimal> invoice_paid { get; set; }
    
        public virtual ICollection<billofentry> billofentries { get; set; }
    }
}
