//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int message_id { get; set; }
        public Nullable<int> message_convoid { get; set; }
        public Nullable<int> message_to { get; set; }
        public Nullable<int> message_from { get; set; }
        public Nullable<System.DateTime> message_stamp { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
