//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ownershiprequest
    {
        public int ownershiprequest_id { get; set; }
        public Nullable<int> ownershiprequest_owner { get; set; }
        public Nullable<int> ownershiprequest_newowner { get; set; }
        public string ownershiprequest_acceptance { get; set; }
        public Nullable<int> ownershiprequest_product { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual product product { get; set; }
    }
}
