
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CiroService.EFDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class productlog
{

    public int productlog_id { get; set; }

    public string productlog_description { get; set; }

    public Nullable<int> product_id { get; set; }



    public virtual product product { get; set; }

}

}
