//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class productlogtype
    {
        public productlogtype()
        {
            this.productlogs = new HashSet<productlog>();
        }
    
        public int productlogtype_id { get; set; }
        public string productlogtype_name { get; set; }
    
        public virtual ICollection<productlog> productlogs { get; set; }
    }
}
