//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class producttype
    {
        public producttype()
        {
            this.products = new HashSet<product>();
        }
    
        public int producttype_id { get; set; }
        public string producttype_name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
