//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class productlog
    {
        public int productlog_id { get; set; }
        public Nullable<int> productlog_product { get; set; }
        public Nullable<int> productlog_user { get; set; }
        public string productlog_dscription { get; set; }
        public Nullable<System.DateTime> productlog_dateLogged { get; set; }
        public string productlog_image { get; set; }
        public Nullable<int> productlog_type { get; set; }
    
        public virtual product product { get; set; }
        public virtual productlogtype productlogtype { get; set; }
        public virtual user user { get; set; }
    }
}
