//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferrequest
    {
        public int transferrequest_id { get; set; }
        public string transferrequest_from { get; set; }
        public string transferrequest_to { get; set; }
        public string transferrequest_verdict { get; set; }
        public Nullable<int> transferrequest_user { get; set; }
        public Nullable<int> transferrequest_product { get; set; }
        public string transferrequest_description { get; set; }
        public string transferrequest_reason { get; set; }
        public Nullable<System.DateTime> transferrequest_requestDate { get; set; }
        public Nullable<System.DateTime> transferrequest_approvalDate { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
