<<<<<<< HEAD
=======

>>>>>>> newService
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferlist
    {
        public int transferlist_id { get; set; }
        public string transferlist_from { get; set; }
        public string transferlist_to { get; set; }
        public Nullable<int> transferlist_user_id { get; set; }
        public Nullable<int> transferlist_product_id { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
=======

namespace CiroService.EFDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class transferlist
{

    public int transferlist_id { get; set; }

    public string transferlist_from { get; set; }

    public string transferlist_to { get; set; }

    public Nullable<int> transferlist_product { get; set; }



    public virtual product product1 { get; set; }

}

>>>>>>> newService
}
