//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.billofentries = new HashSet<billofentry>();
            this.messages = new HashSet<message>();
            this.messages1 = new HashSet<message>();
            this.ownershiprequests = new HashSet<ownershiprequest>();
            this.ownershiprequests1 = new HashSet<ownershiprequest>();
            this.productlogs = new HashSet<productlog>();
            this.releaserequests = new HashSet<releaserequest>();
            this.transferrequests = new HashSet<transferrequest>();
            this.warehouses = new HashSet<warehouse>();
            this.warehouseemployees = new HashSet<warehouseemployee>();
            this.warehousetasks = new HashSet<warehousetask>();
        }
    
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string user_fname { get; set; }
        public string user_sname { get; set; }
        public string user_password { get; set; }
        public Nullable<int> usertype_id { get; set; }
    
        public virtual ICollection<billofentry> billofentries { get; set; }
        public virtual ICollection<message> messages { get; set; }
        public virtual ICollection<message> messages1 { get; set; }
        public virtual ICollection<ownershiprequest> ownershiprequests { get; set; }
        public virtual ICollection<ownershiprequest> ownershiprequests1 { get; set; }
        public virtual ICollection<productlog> productlogs { get; set; }
        public virtual ICollection<releaserequest> releaserequests { get; set; }
        public virtual ICollection<transferrequest> transferrequests { get; set; }
        public virtual usertype usertype { get; set; }
        public virtual ICollection<warehouse> warehouses { get; set; }
        public virtual ICollection<warehouseemployee> warehouseemployees { get; set; }
        public virtual ICollection<warehousetask> warehousetasks { get; set; }
    }
}
