<<<<<<< HEAD
=======

>>>>>>> newService
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usertype()
        {
            this.users = new HashSet<user>();
        }
    
        public int usertype_id { get; set; }
        public string usertype_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
=======

namespace CiroService.EFDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class usertype
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public usertype()
    {

        this.users = new HashSet<user>();

    }


    public int usertype_id { get; set; }

    public string usertype_name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<user> users { get; set; }

}

>>>>>>> newService
}
