//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertype
    {
        public usertype()
        {
            this.users = new HashSet<user>();
        }
    
        public int usertype_id { get; set; }
        public string usertype_name { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
