//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouseemployee
    {
        public int warehouseemployee_id { get; set; }
        public Nullable<int> warehouseemployee_employee { get; set; }
        public Nullable<int> warehouseemployee_warehouse { get; set; }
    
        public virtual user user { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
