
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CiroService.EFDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class warehousestock
{

    public int warehousestock_id { get; set; }

    public Nullable<int> product_id_warehousestock { get; set; }

    public Nullable<int> warehouse_id_warehousestock { get; set; }

    public Nullable<System.DateTime> lastdatechecked { get; set; }

    public Nullable<int> numberofchecks { get; set; }



    public virtual product product { get; set; }

    public virtual warehouse warehouse { get; set; }

}

}
