//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warehouse()
        {
            this.locations = new HashSet<location>();
            this.warehousestocks = new HashSet<warehousestock>();
        }
    
        public int warehouse_id { get; set; }
        public string warehouse_name { get; set; }
        public string warehouse_location { get; set; }
        public Nullable<int> warehouse_size { get; set; }
        public Nullable<int> warehouse_user { get; set; }
        public Nullable<int> warehouse_isles { get; set; }
        public Nullable<int> warehouse_warehousetype { get; set; }
        public string warehouse_image { get; set; }
        public string warehouse_description { get; set; }
        public Nullable<System.DateTime> warehouse_established { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> locations { get; set; }
        public virtual user user { get; set; }
        public virtual warehousetype warehousetype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehousestock> warehousestocks { get; set; }
    }
}
