<<<<<<< HEAD
=======

>>>>>>> newService
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehousetype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warehousetype()
        {
            this.warehouses = new HashSet<warehouse>();
        }
    
        public int warehousetype_id { get; set; }
        public string warehousetype_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse> warehouses { get; set; }
    }
=======

namespace CiroService.EFDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class warehousetype
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public warehousetype()
    {

        this.warehouses1 = new HashSet<warehouse>();

    }


    public int warehousetype_id { get; set; }

    public string warehousetype_name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<warehouse> warehouses1 { get; set; }

}

>>>>>>> newService
}
