//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiroService.EFDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehousestock
    {
        public int warehousestock_id { get; set; }
        public Nullable<System.DateTime> warehousestock_lastchecked { get; set; }
        public Nullable<int> warehousestock_warehouse { get; set; }
        public Nullable<int> warehousestock_product { get; set; }
    
        public virtual product product { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
