
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CiroService.EFDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class warehousestocklayout
{

    public int product_id { get; set; }

    public string product_name { get; set; }

    public Nullable<decimal> product_price { get; set; }

    public Nullable<int> product_quantity { get; set; }

    public Nullable<int> user_id { get; set; }

    public Nullable<int> producttype_id { get; set; }

    public int warehousestock_id { get; set; }

    public Nullable<int> product_id_warehousestock { get; set; }

    public Nullable<int> warehouse_id_warehousestock { get; set; }

}

}
